[tools]
ghalint = "1.5.5"
pinact = "4.0.0"

[tasks."build:ghcache"]
description = "Builds the docker container"
run = "docker build --cache-from type=gha --cache-to type=gha,mode=max -t ${IMAGE_TAG:-coding-agent-sandbox} ."

[tasks.build]
description = "Builds the docker container"
run = "docker build -t ${IMAGE_TAG:-coding-agent-sandbox} ."

[tasks.run]
description = "Runs the docker container for manual testing"
run = "docker run -ti -v ~/.config/gemini:/home/ubuntu/.gemini --rm coding-agent-sandbox"

[tasks.docs]
alias = "doc"
description = "Update tasks in README"
run = "mise generate task-docs -i -o README.md"

[tasks."actions:lint"]
description = 'Lint GitHub Actions workflows and actions with ghalint'
run = ["ghalint run", "ghalint run-action"]
